version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: noter-backend
      POSTGRES_USER: noter-backend
      POSTGRES_PASSWORD: noter-backend
      restart: always
    expose:
      - "5432"

  noter-backend:
    environment:
      DJANGO_SETTINGS_MODULE: noter_backend.dev_settings
      DATABASE_URL: 'postgres://noter-backend:noter-backend@db:5432'
      NOTER_DB_HOST: 'db'
      NOTER_GS_PROJECT_ID: ''
      # If NOTER_GS_MEDIA_BUCKET_NAME is empty, local disk will be used.
      # You may lose the data if the disk is not persistent!
      NOTER_GS_MEDIA_BUCKET_NAME: ''

    build:
      context: .
      dockerfile: Dockerfile
    image: noter-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/noter-backend
    entrypoint: /noter-backend/docker-compose-entrypoint.sh
    depends_on:
      - db
